### ISSUE TITLE
Small graphical issues in BEAUti

### ISSUE THREAD

**Issue by bjoelle** [CompEvol/BeastFX#12]
All screenshots from BEAUti in the BEAST 2.7 release on Windows, no packages installed
- some tooltips are blank, seems to affect combo boxes particularly (I've seen it on the clock model & substitution model boxes)
![blank_tooltip](https://user-images.githubusercontent.com/14575423/190653391-c2ccb3b9-f695-46ec-b7de-eba2aefb287e.png)

- after adding the "Starting tree" panel, many tooltips show "Starting tree" including on other panels
![pb_tooltip-2](https://user-images.githubusercontent.com/14575423/190653390-d3ce5569-3ab7-49dd-8e94-e82aaf6c04af.png)
![pb_tooltip](https://user-images.githubusercontent.com/14575423/190653394-0b5e8f05-87c4-40df-824e-708b003c06dc.png)

- the icon is a black square, both in the title bar and in the Windows menu bar
![pb_icon](https://user-images.githubusercontent.com/14575423/190653392-4759fd21-32ef-4539-a766-4b53e6c52326.png)

**Comment by rbouckaert** [comment]
Thanks Joelle! Let me know if you find any others.
