### ISSUE TITLE
Checkboxes do not trigger refresh of the GUI in BEAUti

### ISSUE THREAD

**Issue by bjoelle** [CompEvol/BeastFX#16]
When toggling the estimate checkbox, the panel doesn't refresh so things like the prior list do not get updated. Going to another panel then coming back does refresh properly.
See screenshot (on Windows 10, BeastFX master branch)
![checkbox](https://user-images.githubusercontent.com/14575423/192536155-80d83e13-ebee-4816-9a30-63fa68ea77cc.png)

**Comment by rbouckaert** [comment]
Thanks for spotting, Joelle! Should be available in the v2.7.1 release, which is imminent.
