### ISSUE TITLE
Missing examples directory

### ISSUE THREAD

**Issue by aezarebski** [CompEvol/BeastFX#17]
https://github.com/CompEvol/BeastFX/blob/c2cefbd17b7ca5072e443bbe633428c4a6514d7d/build.xml#L194

When building this with `ant addon` I got an error:

```
BUILD FAILED
/home/aez/Documents/BeastFX/build.xml:194: /home/aez/Documents/BeastFX/examples does not exist.
```

Creating an empty `examples` directory fixed this. Perhaps add a bogus file `BeastFX/examples/.gitkeep` to ensure that this directory is present, or add a condition to the build script to only attempt the copy if it is present? 

In case it is relevant:
```
Ubuntu 20.04.5 LTS x86_64
openjdk version "17.0.4.1" 2022-08-12 LTS
OpenJDK Runtime Environment Zulu17.36+17-CA (build 17.0.4.1+1-LTS)
OpenJDK 64-Bit Server VM Zulu17.36+17-CA (build 17.0.4.1+1-LTS, mixed mode, sharing)
```

**Comment by rbouckaert** [comment]
This looks like a bug in the `build.xml` file. BeastFX shares the examples directory with the beast2 repository, from where it should pick up its examples. I updated `build.xml` so `ant addon` should work now.
