### ISSUE TITLE
BEAUti 2.7.4 package manager buttons don't display

### ISSUE THREAD

**Issue by laduplessis** [CompEvol/BeastFX#60]
The buttons on the package manager aren't scaled and the text cannot be read (see below). The close window button also has no effect (the red cross on the top left) and I can only exit the package manager by pressing the rightmost button at the bottom. This is BEAUti 2.7.4 on macOS 12.6.3.

<img width="1042" alt="Screenshot 2023-06-23 at 15 22 11" src="https://github.com/CompEvol/BeastFX/assets/8872277/315770a7-9eeb-45a6-a653-381c103a5bd0">

**Comment by rbouckaert** [comment]
The problem with the buttons seems to be due to the bootstrap theme, and does not occur with the default theme (menu `View => Theme Default`), so it may requires fixing of the style sheet for the bootstrap theme.
