### ISSUE TITLE
Taxon set editor buttons don't display properly

### ISSUE THREAD

**Issue by laduplessis** [CompEvol/BeastFX#61]
The left and right arrows on the taxon set editor are not displayed. This is BEAUti 2.7.4 on macOS 12.6.3.

<img width="581" alt="beast2_homochronous_tMRCA" src="https://github.com/CompEvol/BeastFX/assets/8872277/44a79c4d-5268-4164-bb71-b4075fdf6bec">

**Comment by rbouckaert** [comment]
This is probably be due to the same problem as the button widths in #60.
After fixing the bootstrap template, the buttons showed like expected.
