### ISSUE TITLE
Problems quitting BEAST 2.7.4 GUI on macOS

### ISSUE THREAD

**Issue by laduplessis** [CompEvol/BeastFX#63]
Going to BEAST -> Quit BEAST or using the shortcut CMD-Q has no effect. Only way to quit BEAST 2.7.4 GUI on macOS is to close the window (press the red X at top left), which also exits the application. There is no dialogue box about saving the output anymore as in earlier versions. This is BEAST 2.7.4 on macOS 12.6.3.

**Comment by rbouckaert** [comment]
Tested on OS X 12.6.6 and it appears to work: CMD-Q quits BEAST, clicking the x at top left closes the dialog (but not the console window, so when running an analysis it does not interrupt the run), so I am closing this issue. Please re-open if it does not work for other cases or this behaviour is not what is expected.
