### ISSUE TITLE
Ambiguous data type dialogue box doesn't always get focus

### ISSUE THREAD

**Issue by laduplessis** [CompEvol/BeastFX#66]
When dragging an alignment into the BEAUti window with an ambiguous data type the "Add partition" dialogue box to select the data type (nucleotide, AA, etc.) doesn't always get the focus (remains hidden behind other windows), while BEAUti appears to hang. This is BEAUti 2.7.4 on macOS 12.6.3

**Comment by rbouckaert** [comment]
This may be a duplicate of #58 that is fixed now.

**Comment by laduplessis** [comment]
Yes it is
