### ISSUE TITLE
Changing the colour of the validation label makes it invisible

### ISSUE THREAD

**Issue by bjoelle** [CompEvol/BeastFX#70]
So code like this makes the validation label invisible if the validation fails:
```
    public void validateInput() {
		try {
			augTree.initAndValidate();
			if (m_validateLabel != null) {
				m_validateLabel.setVisible(false);
			}
		} catch (Exception e) {
			Log.err.println("Validation message: " + e.getMessage());
			if (m_validateLabel != null) {
				m_validateLabel.setTooltip("Validation error: " + e.getMessage());
				m_validateLabel.setColor("red"); // commenting this line out solves the problem
				m_validateLabel.setVisible(true);
			}
			notifyValidationListeners(ValidationStatus.IS_INVALID);
		}
		repaint();
	}
```

As far as I can tell, this comes from the fact that `SmallLabel.setColour` replaces the style of the label entirely, and so also removes the height and width set when creating the label.

**Comment by rbouckaert** [comment]
@bjoelle Good catch!
Does [31b532b](https://github.com/CompEvol/BeastFX/commit/31b532b79ce4173e20fe348e54d0ef6aba4ec0c7) fix the problem?

**Comment by bjoelle** [comment]
So the label now appears correctly, but it still doesn't change colour - it's orange (which I guess is the default ?) not red

**Comment by rbouckaert** [comment]
Thanks -- it was indeed the style being completely replaced. Maintaining the bits other than colour fixed it.
