### ISSUE TITLE
Licence?  Readme with build instructions?

### ISSUE THREAD

**Issue by tgvaughan** [CompEvol/BeastFX#9]
At the moment this repository looks a bit bare, especially for something that's of such central importance.   We need to include a license somewhere for sure, and it would be fantastic if the readme contained a bit more detail and some instructions on how to build this package from the source.

**Comment by rbouckaert** [comment]
Sorry for the omission -- I added the license form BEAST 2, and added some text in the readme. I suppose what is really needed is an update of the [developers tutorial](http://www.beast2.org/package-development-guide/writing-a-beast-2-package/), now things have gotten a more complex to set up.

Do you think the instructions in the [readme](https://github.com/CompEvol/BeastFX/blob/master/README.md) are sufficient (apart from building of the BEAST.app addon, which is currently broken)?
